//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos_Cursos
    {
        public int id { get; set; }
        public int alumno { get; set; }
        public int curso { get; set; }
        public short año { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Cursos Cursos { get; set; }
    }
}
