//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clases
    {
        public Clases()
        {
            this.Asistencias = new HashSet<Asistencias>();
        }
    
        public int id { get; set; }
        public int asignatura { get; set; }
        public int profesor { get; set; }
        public int curso { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Asignaturas Asignaturas { get; set; }
        public virtual ICollection<Asistencias> Asistencias { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Encargados Encargados { get; set; }
    }
}
