//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public Cursos()
        {
            this.Clases = new HashSet<Clases>();
            this.Alumnos_Cursos = new HashSet<Alumnos_Cursos>();
        }
    
        public int id { get; set; }
        public short generacion { get; set; }
        public string codigo { get; set; }
    
        public virtual ICollection<Clases> Clases { get; set; }
        public virtual ICollection<Alumnos_Cursos> Alumnos_Cursos { get; set; }
    }
}
