//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encargados
    {
        public Encargados()
        {
            this.Clases = new HashSet<Clases>();
            this.CuentasUsuario = new HashSet<CuentasUsuario>();
        }
    
        public int id { get; set; }
        public string rut { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string sexo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Clases> Clases { get; set; }
        public virtual ICollection<CuentasUsuario> CuentasUsuario { get; set; }
    }
}
