//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscuelaEntities : DbContext
    {
        public EscuelaEntities()
            : base("name=EscuelaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alumnos> Alumnos { get; set; }
        public DbSet<Asignaturas> Asignaturas { get; set; }
        public DbSet<Asistencias> Asistencias { get; set; }
        public DbSet<Clases> Clases { get; set; }
        public DbSet<CuentasUsuario> CuentasUsuario { get; set; }
        public DbSet<Cursos> Cursos { get; set; }
        public DbSet<Encargados> Encargados { get; set; }
        public DbSet<Notas> Notas { get; set; }
        public DbSet<Alumnos_Cursos> Alumnos_Cursos { get; set; }
    }
}
